#!/usr/bin/env python3
"""gen_fw_headers.py — emit qn_table.h / qn_input.h C arrays for the RV32
hardware-dispatch firmware build (qn_main.c), from a quartznet_ref.py output
directory.

Usage:
    python3 gen_fw_headers.py <golden_dir> <t_out> <in_ch>

Reads <golden_dir>/quartznet_desc.bin and quartznet_input.bin, writes
qn_table.h and qn_input.h into the current directory (firmware/quartznet/).
These are linked-in const arrays -- the RV32 build has no filesystem, so the
mp3-to-text pipeline's file-based staging (mp3_to_text.py / qn_transcribe.c)
doesn't apply here. Weights/qparams are NOT included: on the real part (and
in the sim/verilator_qn shim) they live in QSPI, which the CPU never touches
directly -- see qn_accel.h.
"""
import pathlib
import sys


def emit(path: pathlib.Path, arr_name: str, data: bytes) -> None:
    lines = [
        f"/* {path.name} -- generated by gen_fw_headers.py from "
        f"{arr_name}; do not edit by hand */",
        "#include <stdint.h>",
        f"static const uint8_t {arr_name}[] = {{",
    ]
    for i in range(0, len(data), 16):
        lines.append(",".join(str(b) for b in data[i:i + 16]) + ",")
    lines.append("};")
    lines.append(f"#define {arr_name.upper()}_LEN {len(data)}u")
    path.write_text("\n".join(lines) + "\n")


def main() -> None:
    if len(sys.argv) != 4:
        sys.exit(f"usage: {sys.argv[0]} <golden_dir> <t_out> <in_ch>")
    golden_dir = pathlib.Path(sys.argv[1])
    t_out = int(sys.argv[2])
    in_ch = int(sys.argv[3])

    table = (golden_dir / "quartznet_desc.bin").read_bytes()
    inp = (golden_dir / "quartznet_input.bin").read_bytes()

    emit(pathlib.Path("qn_table.h"), "qn_table_bin", table)
    emit(pathlib.Path("qn_input.h"), "qn_input_bin", inp)
    with open("qn_input.h", "a") as f:
        f.write(f"#define QN_FW_T_OUT {t_out}\n")
        f.write(f"#define QN_FW_IN_CH {in_ch}\n")

    print(f"wrote qn_table.h ({len(table)} B) and qn_input.h ({len(inp)} B, "
          f"t_out={t_out} in_ch={in_ch})")


if __name__ == "__main__":
    main()
