/* qn_main.c — bare-metal PicoRV32 entry point that drives the QuartzNet
 * table-walking accelerator over MMIO and prints a CTC transcript over UART.
 *
 * Bare-metal analogue of qn_transcribe.c (which runs the same steps on x86
 * with fopen/fread/printf against files on disk). There is no filesystem
 * here: the descriptor table and mel input are linked-in const arrays
 * (qn_table.h / qn_input.h, generated by `make gen-headers`); weights and
 * qparams are NOT linked in at all -- they live in QSPI, which qn_load()
 * never dereferences when called with NULL blob pointers, and which only
 * the accelerator's own table walker (not this CPU) ever reads.
 *
 * QSPI layout this firmware assumes (must match whatever loaded QSPI --
 * sim/verilator_qn's --qspi-image today, a real flash programmer later):
 * weights at byte 0, qparams 4-byte-aligned right after, descriptor table
 * 4-byte-aligned right after that -- exactly rtl/tb/quartznet_tb.cpp's own
 * w_base=0 / q_base / t_base convention, derived here from the table
 * header's weight_bytes/qparam_bytes fields rather than hardcoded.
 */

#include "qn_accel.h"
#include "syscalls.h"
#include "qn_table.h"
#include "qn_input.h"

/* N_CLASSES is 29 for every config this repo emits; rounded up generously so
 * a future wider label set doesn't silently overflow this static buffer. */
#define QN_FW_LOGITS_PITCH_MAX 64

static int8_t qn_logits_buf[QN_FW_T_OUT * QN_FW_LOGITS_PITCH_MAX];
static char   qn_text_buf[512];

static void die(const char *msg, int code)
{
    uart_puts(msg);
    uart_putc('\n');
    sim_exit(code);
}

int main(void)
{
    qn_model_t m;
    int rc = qn_load(&m, qn_table_bin, QN_TABLE_BIN_LEN, NULL, 0, NULL, 0, QN_FW_T_OUT);
    if (rc != QN_OK) die("qn_load failed", 1);
    if ((int)m.in_ch != QN_FW_IN_CH) die("qn_input.h in_ch mismatch", 1);
    if ((int)m.buf_ch[QN_BUF_LOGITS] > QN_FW_LOGITS_PITCH_MAX) die("logits pitch too wide", 1);

    uint32_t w_base  = 0u;
    uint32_t qp_base = (w_base + m.weight_bytes + 3u) & ~3u;
    uint32_t t_base  = (qp_base + m.qparam_bytes + 3u) & ~3u;
    qn_hw_map_t map = {
        .table_base = t_base, .w_blob_base = w_base,
        .qp_blob_base = qp_base, .arena_base = 0u
    };

    rc = qn_set_input_hw(&m, (const int8_t *)qn_input_bin, &map);
    if (rc != QN_OK) die("qn_set_input_hw failed", 1);

    uint32_t cycles = 0;
    rc = qn_run_hw(&m, &map, &cycles);
    if (rc == QN_ERR_HW_TIMEOUT)    die("qn_run_hw timed out", 1);
    if (rc == QN_ERR_HW_BAD_IN_OFF) die("qn_run_hw: err_bad_in_off latched", 1);
    if (rc != QN_OK)                die("qn_run_hw failed", 1);

    rc = qn_read_logits_hw(&m, qn_logits_buf, &map);
    if (rc != QN_OK) die("qn_read_logits_hw failed", 1);

    int n = qn_ctc_greedy_buf(&m, qn_logits_buf, (int)m.buf_ch[QN_BUF_LOGITS],
                              qn_text_buf, (int)sizeof(qn_text_buf));
    if (n < 0) die("qn_ctc_greedy_buf failed", 1);

    uart_puts("cycles=");     uart_putu32(cycles); uart_putc('\n');
    uart_puts("transcript(\""); uart_puts(qn_text_buf); uart_puts("\")\n");

    sim_exit(0);
    return 0;
}
