/* tiny_vad_infer.c
 *
 * int8 inference engine for TinyVAD.
 * Compiles for both x86 (host tests) and riscv32-unknown-elf (bare-metal).
 *
 * All arithmetic is int8/int32 — no floats, no malloc, no libc beyond stdint.h.
 * Each layer function is designed to map directly onto the int8 MAC accelerator
 * defined in Stage 3 (each inner loop = one dot-product / matvec call).
 *
 * Quantization convention (matches TFLite full-integer quantization):
 *   float_val = scale * (int8_val - zero_point)
 *
 * Layer outputs are requantized between each layer using the precomputed
 * fixed-point multiplier (LAYERX_MULT, LAYERX_RSHIFT) from tiny_vad_weights.h.
 */

#include <stdint.h>
#include "tiny_vad_infer.h"
#include "tiny_vad_weights.h"   /* generated by export_weights.py */

/* ── Static scratch buffers ──────────────────────────────────────────────────
 * Two ping-pong buffers are enough since we process layers sequentially.
 * Sizes are the maximum needed across all layers.                           */

static int8_t buf0[TINYVAD_BUF0_SIZE];   /* conv0 output  [32, 25] */
static int8_t buf1[TINYVAD_BUF1_SIZE];   /* conv1 output  [64, 13] */
static int8_t buf2[TINYVAD_BUF2_SIZE];   /* pool  output  [64]     */
static int8_t buf3[TINYVAD_BUF3_SIZE];   /* fc0   output  [32]     */

/* ── Fixed-point multiply ─────────────────────────────────────────────────────
 *
 * Multiplies a 32-bit accumulator by a Q31 fixed-point multiplier, then
 * right-shifts by `shift`.  Matches TFLite's MultiplyByQuantizedMultiplier().
 *
 * result ≈ x * (q_mult * 2^{-31}) * 2^{-shift}
 *
 * This is the exact operation the int8 MAC accelerator will implement in HW.
 */
static inline int32_t requantize(int32_t x, int32_t q_mult, int32_t shift)
{
    int64_t val = (int64_t)q_mult * (int64_t)x;
    /* round toward nearest by adding 2^30 before the Q31 shift */
    val += (1LL << 30);
    val >>= 31;
    /* apply right-shift (shift > 0) or left-shift (shift < 0) */
    if (shift > 0) {
        val += (1LL << (shift - 1));   /* round to nearest */
        val >>= shift;
    } else if (shift < 0) {
        val <<= (-shift);
    }
    return (int32_t)val;
}

static inline int8_t clamp_i8(int32_t x)
{
    if (x >  127) return  127;
    if (x < -128) return -128;
    return (int8_t)x;
}

/* ── Conv1d ────────────────────────────────────────────────────────────────────
 *
 * 1D convolution with:
 *   - int8 weights (zero_point always 0 for symmetric quantization)
 *   - int32 biases (pre-scaled to input*weight quantization space)
 *   - input zero-point subtracted inside accumulation
 *   - output requantized and optionally ReLU-clamped
 *
 * Weight layout: w[out_ch][in_ch][kernel]  (row-major, C order)
 * Input  layout: inp[in_ch][in_len]
 * Output layout: out[out_ch][out_len]
 *
 * This function will be the primary target for accelerator offload in Stage 3.
 * The inner i/k loop = one MAC operation per cycle on the 8-lane int8 array.
 */
static void conv1d(
    const int8_t  *inp,           /* [in_ch * in_len]                */
    const int8_t  *w,             /* [out_ch * in_ch * kernel]       */
    const int32_t *b,             /* [out_ch]                        */
    int8_t        *out,           /* [out_ch * out_len]              */
    int in_ch,  int in_len,
    int out_ch, int out_len,
    int kernel, int stride, int pad,
    int in_zp, int out_zp,
    int32_t q_mult, int32_t rshift,
    int relu)
{
    for (int oc = 0; oc < out_ch; oc++) {
        for (int t = 0; t < out_len; t++) {
            int32_t acc = b[oc];
            for (int ic = 0; ic < in_ch; ic++) {
                for (int k = 0; k < kernel; k++) {
                    int pos = t * stride + k - pad;
                    int32_t x = 0;
                    if (pos >= 0 && pos < in_len) {
                        x = (int32_t)inp[ic * in_len + pos] - in_zp;
                    }
                    /* weight zero-point is 0 (symmetric), so no subtraction */
                    int32_t wv = (int32_t)w[(oc * in_ch + ic) * kernel + k];
                    acc += x * wv;
                }
            }
            int32_t r = requantize(acc, q_mult, rshift) + out_zp;
            if (relu && r < out_zp) r = out_zp;  /* ReLU: clamp at 0.0 = out_zp */
            out[oc * out_len + t] = clamp_i8(r);
        }
    }
}

/* ── GlobalAvgPool1d ──────────────────────────────────────────────────────────
 *
 * Average over the time dimension.  Input [ch, len] → output [ch].
 * Requantizes if input/output scales differ (general case).
 */
static void global_avg_pool(
    const int8_t *inp,    /* [ch * len] */
    int8_t       *out,    /* [ch]       */
    int ch, int len,
    int in_zp,  int out_zp,
    int32_t q_mult, int32_t rshift)
{
    for (int c = 0; c < ch; c++) {
        int32_t sum = 0;
        for (int t = 0; t < len; t++) {
            sum += (int32_t)inp[c * len + t] - in_zp;
        }
        /* divide by len using integer arithmetic, then requantize */
        /* sum / len ≈ sum * inv_len; here we keep it as integer avg */
        int32_t avg = (sum + len / 2) / len;   /* round-to-nearest */
        int32_t r = requantize(avg, q_mult, rshift) + out_zp;
        out[c] = clamp_i8(r);
    }
}

/* ── Dense (fully-connected) ─────────────────────────────────────────────────
 *
 * Matrix-vector multiply.
 * Weight layout: w[out][in]  (row-major)
 * This is a direct matvec — the primary kernel for the Stage 3 accelerator.
 */
static void dense(
    const int8_t  *inp,   /* [in]    */
    const int8_t  *w,     /* [out*in] */
    const int32_t *b,     /* [out]   */
    int8_t        *out,   /* [out]   */
    int in, int out_dim,
    int in_zp, int out_zp,
    int32_t q_mult, int32_t rshift,
    int relu)
{
    for (int o = 0; o < out_dim; o++) {
        int32_t acc = b[o];
        for (int i = 0; i < in; i++) {
            int32_t x  = (int32_t)inp[i] - in_zp;
            int32_t wv = (int32_t)w[o * in + i];
            acc += x * wv;
        }
        int32_t r = requantize(acc, q_mult, rshift) + out_zp;
        if (relu && r < out_zp) r = out_zp;
        out[o] = clamp_i8(r);
    }
}

/* ── Public inference function ───────────────────────────────────────────────
 *
 * The input tensor is [N_FRAMES, N_MEL] row-major.
 * Conv layers expect [ch, len], so we reinterpret as [N_MEL, N_FRAMES]
 * (same memory — just a different logical view matching x.permute(0,2,1)
 * in the PyTorch model).
 */
int tiny_vad_infer(const int8_t *input, int8_t *logits)
{
    /* input layout:  [N_FRAMES=49, N_MEL=40]  row-major
     * conv0 expects: [in_ch=40, in_len=49]
     * These are the same array — only the stride interpretation changes.
     * We pass input directly; the loop indices in conv1d treat dim0 as
     * channels and dim1 as time, which matches [N_MEL, N_FRAMES].        */

    /* Layer 0: Conv0 + ReLU → buf0 [32, 25] */
    conv1d(input,
           conv0_w, conv0_b, buf0,
           CONV0_IN_CH, CONV0_IN_LEN,
           CONV0_OUT_CH, CONV0_OUT_LEN,
           CONV0_KERNEL, CONV0_STRIDE, CONV0_PAD,
           CONV0_ZP_IN, CONV0_ZP_OUT,
           CONV0_MULT, CONV0_RSHIFT,
           /*relu=*/1);

    /* Layer 1: Conv1 + ReLU → buf1 [64, 13] */
    conv1d(buf0,
           conv1_w, conv1_b, buf1,
           CONV1_IN_CH, CONV1_IN_LEN,
           CONV1_OUT_CH, CONV1_OUT_LEN,
           CONV1_KERNEL, CONV1_STRIDE, CONV1_PAD,
           CONV1_ZP_IN, CONV1_ZP_OUT,
           CONV1_MULT, CONV1_RSHIFT,
           /*relu=*/1);

    /* Layer 2: GlobalAvgPool → buf2 [64] */
    global_avg_pool(buf1, buf2,
                    POOL_CH, POOL_LEN,
                    POOL_ZP_IN, POOL_ZP_OUT,
                    POOL_MULT, POOL_RSHIFT);

    /* Layer 3: FC0 + ReLU → buf3 [32] */
    dense(buf2,
          fc0_w, fc0_b, buf3,
          FC0_IN, FC0_OUT,
          FC0_ZP_IN, FC0_ZP_OUT,
          FC0_MULT, FC0_RSHIFT,
          /*relu=*/1);

    /* Layer 4: FC1 → logits [2] */
    dense(buf3,
          fc1_w, fc1_b, logits,
          FC1_IN, FC1_OUT,
          FC1_ZP_IN, FC1_ZP_OUT,
          FC1_MULT, FC1_RSHIFT,
          /*relu=*/0);

    return (logits[1] > logits[0]) ? 1 : 0;
}
