/* tiny_vad_infer.c
 *
 * int8 inference engine for TinyVAD.
 * Compiles for both x86 (host tests) and riscv32-unknown-elf (bare-metal).
 *
 * Tensor layout: [time, channel]  — matches TFLite NHWC convention.
 *   Input    [N_FRAMES=49, N_MEL=40]:  inp[t * N_MEL + mel]
 *   Conv0 out [CONV0_OUT_LEN=25, 32]:  buf[t * 32 + ch]
 *   Conv1 out [CONV1_OUT_LEN=13, 64]:  buf[t * 64 + ch]
 *   Pool  out [64]                  :  flat vector
 *   FC0   out [32]                  :  flat vector
 *   FC1   out [2]                   :  logits
 *
 * Weight layout: [out_ch, in_ch, kernel]  (same C-order as PyTorch after transpose)
 *   w[(oc * in_ch + ic) * kernel + k]
 *
 * Quantization: float = scale * (int8 - zero_point)
 * Per-channel multipliers: one (mult, rshift) pair per output channel.
 */

#include <stdint.h>
#include "tiny_vad_infer.h"
#include "tiny_vad_weights.h"   /* generated by export_weights.py */

/* ── Static scratch buffers ─────────────────────────────────────────────────── */

static int8_t buf0[TINYVAD_BUF0_SIZE];   /* conv0 output [25, 32] */
static int8_t buf1[TINYVAD_BUF1_SIZE];   /* conv1 output [13, 64] */
static int8_t buf2[TINYVAD_BUF2_SIZE];   /* pool  output [64]     */
static int8_t buf3[TINYVAD_BUF3_SIZE];   /* fc0   output [32]     */

/* ── Fixed-point requantize ──────────────────────────────────────────────────
 *
 * result ≈ x * (q_mult * 2^{-31}) * 2^{-shift}
 * shift > 0 = right-shift (typical conv/dense)
 * shift < 0 = left-shift  (pool layer when sc_in > sc_out)
 */
static inline int32_t requantize(int32_t x, int32_t q_mult, int32_t shift)
{
    int64_t val = (int64_t)q_mult * (int64_t)x;
    val += (1LL << 30);   /* round before Q31 shift */
    val >>= 31;
    if (shift > 0) {
        val += (1LL << (shift - 1));
        val >>= shift;
    } else if (shift < 0) {
        val <<= (-shift);
    }
    return (int32_t)val;
}

static inline int8_t clamp_i8(int32_t x)
{
    if (x >  127) return  127;
    if (x < -128) return -128;
    return (int8_t)x;
}

/* ── Conv1d ─────────────────────────────────────────────────────────────────
 *
 * Input  layout: inp[in_len * in_ch]   → inp[t * in_ch + ic]
 * Output layout: out[out_len * out_ch] → out[t * out_ch + oc]
 * Weight layout: w[out_ch * in_ch * kernel] → w[(oc*in_ch + ic)*kernel + k]
 *
 * This [time, channel] layout matches TFLite and makes the inner ic/k loop
 * stride-1 over the weight array — cache friendly for the accelerator.
 */
static void conv1d(
    const int8_t  *inp,
    const int8_t  *w,
    const int32_t *b,
    int8_t        *out,
    int in_ch,  int in_len,
    int out_ch, int out_len,
    int kernel, int stride, int pad,
    int in_zp,  int out_zp,
    const int32_t *q_mult,
    const int32_t *rshift,
    int relu)
{
    for (int t = 0; t < out_len; t++) {
        for (int oc = 0; oc < out_ch; oc++) {
            int32_t acc = b[oc];
            for (int ic = 0; ic < in_ch; ic++) {
                for (int k = 0; k < kernel; k++) {
                    int pos = t * stride + k - pad;
                    if (pos >= 0 && pos < in_len) {
                        /* [time, channel] input: inp[pos * in_ch + ic] */
                        int32_t x  = (int32_t)inp[pos * in_ch + ic] - in_zp;
                        int32_t wv = (int32_t)w[(oc * in_ch + ic) * kernel + k];
                        acc += x * wv;
                    }
                }
            }
            int32_t r = requantize(acc, q_mult[oc], rshift[oc]) + out_zp;
            if (relu && r < out_zp) r = out_zp;
            /* [time, channel] output: out[t * out_ch + oc] */
            out[t * out_ch + oc] = clamp_i8(r);
        }
    }
}

/* ── GlobalAvgPool1d ─────────────────────────────────────────────────────────
 *
 * Input layout: inp[len * ch] → inp[t * ch + c]
 * Output: flat [ch] vector (feeds directly into Dense).
 */
static void global_avg_pool(
    const int8_t *inp,
    int8_t       *out,
    int ch, int len,
    int in_zp, int out_zp,
    int32_t q_mult, int32_t rshift)
{
    for (int c = 0; c < ch; c++) {
        int32_t sum = 0;
        for (int t = 0; t < len; t++) {
            sum += (int32_t)inp[t * ch + c] - in_zp;
        }
        /* round-to-nearest integer average */
        int32_t avg = (sum >= 0) ? (sum + len / 2) / len
                                 : (sum - len / 2) / len;
        int32_t r = requantize(avg, q_mult, rshift) + out_zp;
        out[c] = clamp_i8(r);
    }
}

/* ── Dense (fully-connected) ────────────────────────────────────────────────
 *
 * Input/output are flat 1D vectors — no layout ambiguity.
 * Weight layout: w[out_dim * in] → w[o * in + i]
 */
static void dense(
    const int8_t  *inp,
    const int8_t  *w,
    const int32_t *b,
    int8_t        *out,
    int in, int out_dim,
    int in_zp, int out_zp,
    const int32_t *q_mult,
    const int32_t *rshift,
    int relu)
{
    for (int o = 0; o < out_dim; o++) {
        int32_t acc = b[o];
        for (int i = 0; i < in; i++) {
            int32_t x  = (int32_t)inp[i] - in_zp;
            int32_t wv = (int32_t)w[o * in + i];
            acc += x * wv;
        }
        int32_t r = requantize(acc, q_mult[o], rshift[o]) + out_zp;
        if (relu && r < out_zp) r = out_zp;
        out[o] = clamp_i8(r);
    }
}

/* ── Public inference function ───────────────────────────────────────────────
 *
 * input: int8[N_FRAMES * N_MEL] in row-major [frame, mel] order.
 *        Exactly the layout produced by extract_logmel() quantized to int8.
 *        This is also what TFLite receives, so no transposition needed.
 */
int tiny_vad_infer(const int8_t *input, int8_t *logits)
{
    /* Conv0 + ReLU  →  buf0 [25, 32] */
    conv1d(input,
           conv0_w, conv0_b, buf0,
           CONV0_IN_CH, CONV0_IN_LEN,
           CONV0_OUT_CH, CONV0_OUT_LEN,
           CONV0_KERNEL, CONV0_STRIDE, CONV0_PAD,
           CONV0_ZP_IN, CONV0_ZP_OUT,
           conv0_mult, conv0_rshift,
           /*relu=*/1);

    /* Conv1 + ReLU  →  buf1 [13, 64] */
    conv1d(buf0,
           conv1_w, conv1_b, buf1,
           CONV1_IN_CH, CONV1_IN_LEN,
           CONV1_OUT_CH, CONV1_OUT_LEN,
           CONV1_KERNEL, CONV1_STRIDE, CONV1_PAD,
           CONV1_ZP_IN, CONV1_ZP_OUT,
           conv1_mult, conv1_rshift,
           /*relu=*/1);

    /* GlobalAvgPool  →  buf2 [64] */
    global_avg_pool(buf1, buf2,
                    POOL_CH, POOL_LEN,
                    POOL_ZP_IN, POOL_ZP_OUT,
                    POOL_MULT, POOL_RSHIFT);

    /* FC0 + ReLU  →  buf3 [32] */
    dense(buf2,
          fc0_w, fc0_b, buf3,
          FC0_IN, FC0_OUT,
          FC0_ZP_IN, FC0_ZP_OUT,
          fc0_mult, fc0_rshift,
          /*relu=*/1);

    /* FC1  →  logits [2] */
    dense(buf3,
          fc1_w, fc1_b, logits,
          FC1_IN, FC1_OUT,
          FC1_ZP_IN, FC1_ZP_OUT,
          fc1_mult, fc1_rshift,
          /*relu=*/0);

    return (logits[1] > logits[0]) ? 1 : 0;
}
