/* tiny_vad_infer.h
 *
 * Plain-C int8 inference engine for TinyVAD.
 * No dynamic allocation, no floating point, no C++ — compiles for RV32 bare-metal.
 *
 * Model topology (matches train_tiny_vad.py with BN fused into weights):
 *
 *   Input   [1, 49, 40]  int8  (log-mel, quantized)
 *     ↓
 *   Conv0   [40→32, k=5, stride=2, pad=2] + ReLU  → [32, 25]
 *     ↓
 *   Conv1   [32→64, k=3, stride=2, pad=1] + ReLU  → [64, 13]
 *     ↓
 *   AvgPool [64, 13] → [64]
 *     ↓
 *   FC0     [64→32]  + ReLU                        → [32]
 *     ↓
 *   FC1     [32→2]                                  → [2]
 *
 * Usage:
 *   #include "tiny_vad_weights.h"      // generated by export_weights.py
 *   #include "tiny_vad_infer.h"
 *
 *   int8_t logits[2];
 *   tiny_vad_infer(input_int8, logits);
 *   int label = (logits[1] > logits[0]) ? 1 : 0;  // 1=speech, 0=silence
 */

#ifndef TINY_VAD_INFER_H
#define TINY_VAD_INFER_H

#include <stdint.h>

/* ── Model dimensions ───────────────────────────────────────────────────────── */

#define TINYVAD_N_MEL    40
#define TINYVAD_N_FRAMES 49

/* Conv0: in_ch=40, out_ch=32, kernel=5, stride=2, pad=2 */
#define CONV0_IN_CH   40
#define CONV0_OUT_CH  32
#define CONV0_KERNEL   5
#define CONV0_STRIDE   2
#define CONV0_PAD      2
#define CONV0_IN_LEN  49
#define CONV0_OUT_LEN 25   /* floor((49 + 2*2 - 5) / 2) + 1 */

/* Conv1: in_ch=32, out_ch=64, kernel=3, stride=2, pad=1 */
#define CONV1_IN_CH   32
#define CONV1_OUT_CH  64
#define CONV1_KERNEL   3
#define CONV1_STRIDE   2
#define CONV1_PAD      1
#define CONV1_IN_LEN  25
#define CONV1_OUT_LEN 13   /* floor((25 + 2*1 - 3) / 2) + 1 */

/* AvgPool: in=[64,13], out=[64] */
#define POOL_LEN      13
#define POOL_CH       64

/* FC0: 64→32, FC1: 32→2 */
#define FC0_IN   64
#define FC0_OUT  32
#define FC1_IN   32
#define FC1_OUT   2

/* ── Static scratch buffers (sizes in int8) ─────────────────────────────────── */
/* Worst-case intermediate tensors (all layers fit in ~2 KB) */

#define TINYVAD_BUF0_SIZE  (CONV0_OUT_CH * CONV0_OUT_LEN)   /* 32*25 = 800 */
#define TINYVAD_BUF1_SIZE  (CONV1_OUT_CH * CONV1_OUT_LEN)   /* 64*13 = 832 */
#define TINYVAD_BUF2_SIZE  (POOL_CH)                         /* 64       */
#define TINYVAD_BUF3_SIZE  (FC0_OUT)                         /* 32       */

/* ── Optional hardware-acceleration hooks ────────────────────────────────────
 *
 * Set these to non-NULL before calling tiny_vad_infer() to redirect conv1d
 * and dense layers to hardware.  Default NULL → pure-software fallback.
 *
 * Signatures match the internal static functions in tiny_vad_infer.c exactly.
 */

typedef void (*tinyvad_conv1d_fn)(
    const int8_t *inp, const int8_t *w, const int32_t *b, int8_t *out,
    int in_ch, int in_len, int out_ch, int out_len,
    int kernel, int stride, int pad, int in_zp, int out_zp,
    const int32_t *q_mult, const int32_t *rshift, int relu);

typedef void (*tinyvad_dense_fn)(
    const int8_t *inp, const int8_t *w, const int32_t *b, int8_t *out,
    int in, int out_dim, int in_zp, int out_zp,
    const int32_t *q_mult, const int32_t *rshift, int relu);

extern tinyvad_conv1d_fn tinyvad_conv1d_hook;
extern tinyvad_dense_fn  tinyvad_dense_hook;

/* Pure-software matrix-vector kernel (matches tinyvad_dense_fn). Exposed for the
 * im2col conv lowering in conv_im2col.h and for host correctness tests. */
void tinyvad_dense_sw(
    const int8_t *inp, const int8_t *w, const int32_t *b, int8_t *out,
    int in, int out_dim, int in_zp, int out_zp,
    const int32_t *q_mult, const int32_t *rshift, int relu);

/* ── Public API ─────────────────────────────────────────────────────────────── */

/*
 * tiny_vad_infer()
 *
 * Run full inference on one audio chunk.
 *
 * @param input   int8 array [TINYVAD_N_FRAMES * TINYVAD_N_MEL] = [49*40=1960]
 *                quantized with INPUT_SCALE / INPUT_ZP from tiny_vad_weights.h
 *                layout: row-major [frame][mel]  i.e. inp[frame*40 + mel]
 *                This matches TFLite's NHWC [time, channel] convention.
 *
 * @param logits  output buffer int8[2]
 *                logits[0] = silence score,  logits[1] = speech score
 *                (quantized; compare directly — higher = more likely)
 *
 * Returns:  0 = silence,  1 = speech  (argmax of logits)
 */
int tiny_vad_infer(const int8_t *input, int8_t *logits);

#endif /* TINY_VAD_INFER_H */
