/* tiny_vad_infer.c
 *
 * int8 inference engine for TinyVAD.
 * Compiles for both x86 (host tests) and riscv32-unknown-elf (bare-metal).
 *
 * All arithmetic is int8/int32/int64 — no floats, no malloc.
 *
 * Uses per-channel quantized multipliers (one mult/rshift per output channel),
 * matching TFLite's default per-channel weight quantization.
 *
 * Quantization convention:
 *   float_val = scale * (int8_val - zero_point)
 *
 * The inner MAC loops (conv1d / dense) are the primary targets for
 * accelerator offload in Stage 3.  Each iteration is one int8 multiply-add.
 */

#include <stdint.h>
#include "tiny_vad_infer.h"
#include "tiny_vad_weights.h"   /* generated by export_weights.py */

/* ── Static scratch buffers ─────────────────────────────────────────────────── */

static int8_t buf0[TINYVAD_BUF0_SIZE];   /* conv0 output  [32, 25] */
static int8_t buf1[TINYVAD_BUF1_SIZE];   /* conv1 output  [64, 13] */
static int8_t buf2[TINYVAD_BUF2_SIZE];   /* pool  output  [64]     */
static int8_t buf3[TINYVAD_BUF3_SIZE];   /* fc0   output  [32]     */

/* ── Fixed-point requantize ──────────────────────────────────────────────────
 *
 * Multiplies a 32-bit accumulator by a Q31 fixed-point multiplier then shifts.
 * Matches TFLite MultiplyByQuantizedMultiplier().
 *
 *   result ≈ x * (q_mult * 2^{-31}) * 2^{-shift}
 *
 * shift > 0 → right-shift (typical)
 * shift < 0 → left-shift  (pool layer when sc_in > sc_out)
 */
static inline int32_t requantize(int32_t x, int32_t q_mult, int32_t shift)
{
    int64_t val = (int64_t)q_mult * (int64_t)x;
    val += (1LL << 30);   /* round before Q31 shift */
    val >>= 31;
    if (shift > 0) {
        val += (1LL << (shift - 1));
        val >>= shift;
    } else if (shift < 0) {
        val <<= (-shift);
    }
    return (int32_t)val;
}

static inline int8_t clamp_i8(int32_t x)
{
    if (x >  127) return  127;
    if (x < -128) return -128;
    return (int8_t)x;
}

/* ── Conv1d ─────────────────────────────────────────────────────────────────
 *
 * Per-channel quantized 1-D convolution.
 * Weight layout: w[out_ch * in_ch * kernel]  (C-order: [oc][ic][k])
 * Input  layout: inp[in_ch * in_len]         (C-order: [ic][t])
 * Output layout: out[out_ch * out_len]       (C-order: [oc][t])
 *
 * q_mult[out_ch], rshift[out_ch] — per-channel multipliers.
 *
 * The oc/t/ic/k loops are the accelerator offload target in Stage 3.
 */
static void conv1d(
    const int8_t  *inp,
    const int8_t  *w,
    const int32_t *b,
    int8_t        *out,
    int in_ch,  int in_len,
    int out_ch, int out_len,
    int kernel, int stride, int pad,
    int in_zp,  int out_zp,
    const int32_t *q_mult,
    const int32_t *rshift,
    int relu)
{
    for (int oc = 0; oc < out_ch; oc++) {
        for (int t = 0; t < out_len; t++) {
            int32_t acc = b[oc];
            for (int ic = 0; ic < in_ch; ic++) {
                for (int k = 0; k < kernel; k++) {
                    int pos = t * stride + k - pad;
                    if (pos >= 0 && pos < in_len) {
                        int32_t x  = (int32_t)inp[ic * in_len + pos] - in_zp;
                        int32_t wv = (int32_t)w[(oc * in_ch + ic) * kernel + k];
                        acc += x * wv;
                    }
                }
            }
            int32_t r = requantize(acc, q_mult[oc], rshift[oc]) + out_zp;
            if (relu && r < out_zp) r = out_zp;
            out[oc * out_len + t] = clamp_i8(r);
        }
    }
}

/* ── GlobalAvgPool1d ─────────────────────────────────────────────────────────
 *
 * Input [ch * len] → output [ch].
 * Single per-tensor multiplier (pool has no weight, so per-tensor is correct).
 */
static void global_avg_pool(
    const int8_t *inp,
    int8_t       *out,
    int ch, int len,
    int in_zp, int out_zp,
    int32_t q_mult, int32_t rshift)
{
    for (int c = 0; c < ch; c++) {
        int32_t sum = 0;
        for (int t = 0; t < len; t++) {
            sum += (int32_t)inp[c * len + t] - in_zp;
        }
        /* integer average (round to nearest) */
        int32_t avg = (sum >= 0) ? (sum + len / 2) / len
                                 : (sum - len / 2) / len;
        int32_t r = requantize(avg, q_mult, rshift) + out_zp;
        out[c] = clamp_i8(r);
    }
}

/* ── Dense (fully-connected) ────────────────────────────────────────────────
 *
 * Matrix-vector multiply.
 * Weight layout: w[out * in]  (C-order: [o][i])
 * Per-channel q_mult[out], rshift[out].
 */
static void dense(
    const int8_t  *inp,
    const int8_t  *w,
    const int32_t *b,
    int8_t        *out,
    int in, int out_dim,
    int in_zp, int out_zp,
    const int32_t *q_mult,
    const int32_t *rshift,
    int relu)
{
    for (int o = 0; o < out_dim; o++) {
        int32_t acc = b[o];
        for (int i = 0; i < in; i++) {
            int32_t x  = (int32_t)inp[i] - in_zp;
            int32_t wv = (int32_t)w[o * in + i];
            acc += x * wv;
        }
        int32_t r = requantize(acc, q_mult[o], rshift[o]) + out_zp;
        if (relu && r < out_zp) r = out_zp;
        out[o] = clamp_i8(r);
    }
}

/* ── Public inference function ───────────────────────────────────────────────
 *
 * Input:  int8[N_FRAMES * N_MEL] = int8[49 * 40], row-major [frames][mels].
 * The conv layers expect [channels][time] = [N_MEL][N_FRAMES].
 * Since N_MEL is the "channel" dimension and N_FRAMES is "time", the memory
 * layout is identical — we just reinterpret the strides.
 */
int tiny_vad_infer(const int8_t *input, int8_t *logits)
{
    /* Conv0 + ReLU  →  buf0 [32, 25] */
    conv1d(input,
           conv0_w, conv0_b, buf0,
           CONV0_IN_CH, CONV0_IN_LEN,
           CONV0_OUT_CH, CONV0_OUT_LEN,
           CONV0_KERNEL, CONV0_STRIDE, CONV0_PAD,
           CONV0_ZP_IN, CONV0_ZP_OUT,
           conv0_mult, conv0_rshift,
           /*relu=*/1);

    /* Conv1 + ReLU  →  buf1 [64, 13] */
    conv1d(buf0,
           conv1_w, conv1_b, buf1,
           CONV1_IN_CH, CONV1_IN_LEN,
           CONV1_OUT_CH, CONV1_OUT_LEN,
           CONV1_KERNEL, CONV1_STRIDE, CONV1_PAD,
           CONV1_ZP_IN, CONV1_ZP_OUT,
           conv1_mult, conv1_rshift,
           /*relu=*/1);

    /* GlobalAvgPool  →  buf2 [64] */
    global_avg_pool(buf1, buf2,
                    POOL_CH, POOL_LEN,
                    POOL_ZP_IN, POOL_ZP_OUT,
                    POOL_MULT, POOL_RSHIFT);

    /* FC0 + ReLU  →  buf3 [32] */
    dense(buf2,
          fc0_w, fc0_b, buf3,
          FC0_IN, FC0_OUT,
          FC0_ZP_IN, FC0_ZP_OUT,
          fc0_mult, fc0_rshift,
          /*relu=*/1);

    /* FC1  →  logits [2] */
    dense(buf3,
          fc1_w, fc1_b, logits,
          FC1_IN, FC1_OUT,
          FC1_ZP_IN, FC1_ZP_OUT,
          fc1_mult, fc1_rshift,
          /*relu=*/0);

    return (logits[1] > logits[0]) ? 1 : 0;
}
